import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { getAllPosts, getCategoryBySlug, getPostBySlug } from "@/lib/content";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { Breadcrumbs } from "@/components/breadcrumbs";
import { ArticleBody } from "@/components/article-body";
import { ArticleCard } from "@/components/article-card";
import { NewsletterCta } from "@/components/newsletter-cta";
import { ShareActions } from "@/components/share-actions";
import { JsonLd } from "@/components/seo-json-ld";
import { site } from "@/lib/site";
export function generateStaticParams() { return getAllPosts().map((post) => ({ slug: post.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const post = getPostBySlug(slug); if (!post) return {}; return { title: post.seo.metaTitle, description: post.seo.metaDescription, alternates: { canonical: `/blog/${post.slug}` }, keywords: [post.seo.primaryKeyword, ...post.seo.secondaryKeywords], openGraph: { type: "article", title: post.seo.metaTitle, description: post.seo.metaDescription, url: `${site.domain}/blog/${post.slug}`, images: [{url:post.image.src,width:post.image.width,height:post.image.height,alt:post.image.alt}] }, twitter: { card: "summary_large_image", title: post.seo.metaTitle, description: post.seo.metaDescription, images: [post.image.src] } }; }
export default async function BlogPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const post = getPostBySlug(slug); if (!post) notFound(); const category = getCategoryBySlug(post.categorySlug)!; const related = post.relatedSlugs.map((slug) => getPostBySlug(slug)).filter(Boolean); const headings = post.body.filter((section) => section.type === "heading"); const breadcrumbJsonLd = {"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:site.domain},{"@type":"ListItem",position:2,name:category.name,item:`${site.domain}/category/${category.slug}`},{"@type":"ListItem",position:3,name:post.title,item:`${site.domain}/blog/${post.slug}`}]}; return <><JsonLd value={{"@context":"https://schema.org","@type":"Article",headline:post.title,description:post.excerpt,datePublished:post.publishedAt,dateModified:post.updatedAt || post.publishedAt,author:{"@type":"Person",name:post.author.name},mainEntityOfPage:`${site.domain}/blog/${post.slug}`}}/><JsonLd value={breadcrumbJsonLd}/><SiteHeader/><main className="shell"><div className="article-hero"><Breadcrumbs items={[{label:category.name,href:`/category/${category.slug}`},{label:post.title}]}/><span className="eyebrow">{category.name}</span><h1 className="display">{post.title}</h1><p className="excerpt">{post.excerpt}</p><div className="article-byline"><strong>{post.author.name}</strong><span>{post.author.role}</span><span>Published {new Date(post.publishedAt).toLocaleDateString("en-IN",{month:"short",day:"numeric",year:"numeric"})}</span>{post.updatedAt && <span>Updated {new Date(post.updatedAt).toLocaleDateString("en-IN",{month:"short",day:"numeric",year:"numeric"})}</span>}</div></div><div className="reading-layout"><div><ArticleBody sections={post.body}/><ShareActions title={post.title}/></div><aside className="toc"><strong>In this story</strong>{headings.map((heading) => <a key={heading.text} href={`#${heading.text.toLowerCase().replace(/[^a-z0-9]+/g,"-")}`}>{heading.text}</a>)}</aside></div><section className="section"><div className="section-head"><div><span className="eyebrow">Keep reading</span><h2 className="display">Related stories</h2></div></div><div className="article-grid two">{related.map((item) => item && <ArticleCard key={item.slug} post={item}/>)}</div></section><NewsletterCta/></main><SiteFooter/></>; }
